// Countries/src/REDUX/COMPONENTS/Header.jsx
import React from "react"

export default function Header() {

    function toggleLightDark() {
        // document.documentElement.classList.toggle('dark')
        document.documentElement.classList.toggle('dark');

        console.log(document.documentElement.classList)
    }
    return(

        <div className="w-full h-20 bg-white dark:bg-[#2b3945] flex items-center justify-between p-5">

            <span className="font-bold text-lg dark:text-white">Where in the world?</span>
            <div className="flex items-start gap-2">
                <button onClick={toggleLightDark}>
                    <img src="/Icons/moon.svg" alt="moon" className="w-5 dark:hidden"/>
                    <img src="/Icons/moon-dark.svg" alt="moon" className="w-5 hidden dark:block"/>
                </button>
                <span className="dark:text-white">Dark Mode</span>
            </div>

        </div>
    )
}

// Rock/src/components/Header.vue
<template>

    <header class="w-full max-w-[90%] flex justify-between items-center m-10 p-4 border-2 border-[rgb(99_110_133)] rounded-xl xl:max-w-[700px]">
        <div id="logo" class="bg-[url('./images/logo.svg')] bg-no-repeat bg-cover bg-center w-[162px] h-[100px]"></div>
        <div id="score" class="flex flex-col justify-center items-center gap-3 bg-white h-[90px] w-[100px] rounded-2xl">
            <span class="text-[rgb(84_90_182)] font-bold">score</span>
            <span class="text-[rgb(40_48_78)] text-2xl font-bold">{{ scoreStore.score }}</span>
        </div>
    </header>

</template>

<script setup>
import useScoreStore from '../store/scoreStore';

const scoreStore = useScoreStore()
</script>
